name: HotTimeEvent
main: io.github.potato_y.hottimeevent.HotTimeEvent
version: 1.0

commands:
  HottimeEventTest:
    description: 플러그인이 정상 작동하는지 확인하세요.
    usage: /HET 를 입력하세요.
    aliases:
      - hett
    permission: hottimeevent.het
    permission-message: You do not have permission to use this command.

  GiveAll:
    description: 모든 유저에게 아이템을 지급합니다.
    usage: /GiveAll 혹은 /GiveAll now
    permission: hottimeevent.giveall
    permission-message: You do not have permission to use this command.

permissions:
  hottimeevent.het:
    default: op
  hottimeevent.giveall:
    default: op