name: HotTimeEvent
main: io.github.potato_y.hottimeevent.HotTimeEvent
version: 1.0
author: projectpotatoy@gmail.com
website: https://github.com/Potato-Y/HotTimeEvent


commands:
  #HottimeEventTest:
  #  description: 플러그인이 정상 작동하는지 확인하세요.
  #  usage: /HET 를 입력하세요.
  #  aliases:
  #    - hett
  #  permission: hottimeevent.het
  # permission-message: You do not have permission to use this command.

  GiveAll:
    description: 모든 유저에게 아이템을 지급합니다.
    usage: /GiveAll 혹은 /GiveAll now
    permission: hottimeevent.giveall
    permission-message: You do not have permission to use this command.

  HteReload:
    description: config를 리로드 합니다.
    usage: /htereload
    permission: hottimeevent.reload
    permission-message: You do not have permission to use this command.

  EventList:
    description: 이벤트 목록을 봅니다.
    usage: /eventlist
    permission: hottimeevent.event.list
    permission-message: You do not have permission to use this command.

  EventTest:
    description: 이벤트 아이템을 테스트 합니다.
    usage: /eventtest [Event Name]
    permission: hottimeevent.event.test
    permission-message: You do not have permission to use this command.

permissions:
  hottimeevent.het:
    default: op
  hottimeevent.giveall:
    default: op
  hottmeevent.reload:
    default: op
  hottimeevent.event.list:
    default: op
  hottimeevent.event.test:
    default: op